name: snakevir
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioawk=1.0
  - biopython=1.78
  - blast=2.11.0
  - bwa=0.7.17
  - cap3=10.2011
  - csvkit=1.0.5
  - cutadapt=3.4
  - diamond=2.0.9
  - entrez-direct=13.9
  - ete3=3.1.2
  - flash=1.2.11
  - megahit=1.2.9
  - pandas=1.2.4
  - picard=2.25.4
  - pip=21.1.2
  - python=3.9.4
  - r-base=4.0.5
  - samtools=1.12
  - seqtk=1.3
  - pip:
    - connection-pool==0.0.3
    - snakemake==6.8.0
    - tabulate==0.8.9
